# Generated by Django 5.2.5 on 2025-08-27 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=140)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_acara', models.DateField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album_cover/')),
            ],
            options={
                'verbose_name': 'Album Foto',
                'verbose_name_plural': 'Album Foto',
                'ordering': ['-tanggal_acara'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anggota/')),
                ('bio_singkat', models.CharField(blank=True, max_length=200)),
                ('jabatan', models.CharField(blank=True, max_length=120)),
                ('instagram', models.URLField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=200)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Untuk sorting tampilan')),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('deskripsi_singkat', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('isi', models.TextField()),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('gambar_header', models.ImageField(blank=True, null=True, upload_to='pengumuman/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='album_foto/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('diupload', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Foto',
                'ordering': ['-diupload'],
            },
        ),
    ]
